name: mingpt
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - python<3.10
  - pip
  - tqdm
  - pip:
    - --find-links https://download.pytorch.org/whl/cu113/torch_stable.html
    - --find-links https://storage.googleapis.com/jax-releases/jax_releases.html
    - jax[cuda]
    - torch==1.10.0+cu113
    - torchvision
    - dm-haiku
    - optax